const assert = require('assert');
const fs = require('fs');

const uiSource = fs.readFileSync('src/ui.js', 'utf8');
const controls = fs.readFileSync('src/ui-catalog-controls.js', 'utf8');
const ui = uiSource + '\n' + controls;
const css = fs.readFileSync('style.css', 'utf8');
const i18n = fs.readFileSync('src/i18n.js', 'utf8');
const filters = fs.readFileSync('src/ui-catalog-filters.js', 'utf8');
const genreDescriptions = fs.readFileSync('src/genre-descriptions.js', 'utf8');
const build = fs.readFileSync('build.js', 'utf8');

assert.match(ui, /Lampa\.Component\.add\('yani_catalog', Catalog\)/);
assert.match(uiSource, /function Catalog\(object\)[\s\S]{0,5000}LampaYaniCatalogControls\.create/);
assert.match(uiSource, /function installGenreHeader\(\)/);
assert.match(uiSource, /genre_context: context/);
assert.match(uiSource, /params: \{limit: 30, genres: genreId\}/);
assert.match(uiSource, /var requestedParams = copyParams\(object\.catalog_params \|\| object\.params/);
assert.match(uiSource, /LampaYaniApi\.catalog\(baseParams\)/);
assert.match(uiSource, /function genreDescription\(genre\)/);
assert.match(uiSource, /LampaYaniGenreDescriptions\.resolve\(genre, locale\(\)\)/);
assert.match(genreDescriptions, /function resolve\(genre, language\)/);
assert.match(genreDescriptions, /'isekai':/);
assert.match(genreDescriptions, /function fallback\(genreTitle, language\)/);
assert.match(build, /src\/genre-descriptions\.js/);
assert.match(controls, /genre_context: object\.genre_context/);
assert.match(controls, /catalog_params: params/);
assert.match(css, /\.yani-genre-catalog-header/);
assert.match(css, /\.yani-genre-catalog-header__description/);
assert.doesNotMatch(css, /\.yani-genre-catalog-header__description[\s\S]{0,400}-webkit-line-clamp/);
assert.match(controls, /var sortDefinitions = \[[\s\S]{0,500}sort: 'top'[\s\S]{0,300}sort: 'year'[\s\S]{0,300}sort: 'rating'[\s\S]{0,300}sort: 'rating_counters'[\s\S]{0,300}sort: 'views'[\s\S]{0,300}sort: 'title'[\s\S]{0,300}sort: 'random'/);
assert.match(ui, /function changeSort\(definition\)[\s\S]{0,1600}params\.sort = definition\.sort[\s\S]{0,500}Lampa\.Activity\.replace/);
assert.match(ui, /function scrollToTop\(\)[\s\S]{0,250}comp\.scroll\.reset\(\)[\s\S]{0,150}focusCards\(true\)/);
assert.match(ui, /comp\.on\('controller'/);
assert.match(ui, /function navigationCollection\(\)[\s\S]{0,350}comp\.render\(\)/);
assert.match(ui, /function activeCatalogController\(\)[\s\S]{0,700}enabled\.controller \|\| enabled[\s\S]{0,300}controller\.link === comp/);
assert.match(ui, /function syncNavigationCollection\(\)[\s\S]{0,900}collectionSet\(collection, false, true\)/);
assert.doesNotMatch(ui, /function syncNavigationCollection\(\)[\s\S]{0,700}toolbarTrack\[0\]\.querySelectorAll\('\.selector'\)/);
assert.doesNotMatch(ui, /function syncNavigationCollection\(\)[\s\S]{0,700}Navigator\.setCollection/);
assert.match(ui, /controller\.yaniCatalogOwner === comp \|\| controller\.link === comp/);
assert.match(ui, /comp\.on\('toggle'[\s\S]{0,150}syncNavigationCollection/);
assert.match(ui, /comp\.on\('scroll'[\s\S]{0,150}syncNavigationCollection/);
assert.match(ui, /function patchCatalogController\(controller\)/);
assert.match(ui, /controller\.yaniCatalogOwner = comp/);
assert.match(ui, /var originalStart = comp\.start/);
assert.match(ui, /comp\.start = function \(\)[\s\S]{0,500}patchCatalogController\(activeCatalogController\(\)\)[\s\S]{0,150}syncNavigationCollection\(\)/);
assert.doesNotMatch(ui, /function focusToolbar\(/);
assert.doesNotMatch(ui, /function toolbarHasFocus\(/);
assert.doesNotMatch(ui, /toolbarFocused/);
assert.match(ui, /var lastCatalogCard = null/);
assert.match(ui, /function focusCards\(first\)[\s\S]{0,900}lastCatalogCard \|\| comp\.last[\s\S]{0,500}Navigator\.add\(target\)[\s\S]{0,450}collectionSet\(collection, false, true\)/);
assert.match(ui, /selector: '\.card\.selector'/);
assert.match(ui, /toolbarTrack\.append\(topButton\)/);
assert.match(ui, /function remoteShortcuts\(\)[\s\S]{0,1000}color: 'red'[\s\S]{0,300}color: 'green'[\s\S]{0,300}color: 'yellow'[\s\S]{0,300}color: 'blue'/);
assert.match(ui, /function handleRemoteShortcut\(event\)[\s\S]{0,900}changeSort\(shortcut\.definition\)/);
assert.match(ui, /document\.addEventListener\('keydown', shortcutHandler, true\)/);
assert.match(ui, /document\.removeEventListener\('keydown', shortcutHandler, true\)/);
assert.match(ui, /function shortcutBadge\(number, color\)/);
assert.match(ui, /filterButton\.append\(shortcutBadge\(null, 'blue'\)\)/);
assert.match(ui, /button\.append\(shortcutBadge\(index \+ 1, shortcutColorFor\(definition\)\)\)/);
assert.match(ui, /topButton\.append\(shortcutBadge\(0, ''\)\)/);
assert.doesNotMatch(ui, /createRemoteLegend/);
assert.match(css, /\.yani-catalog-shortcut-badge[\s\S]{0,500}border-radius/);
assert.match(css, /\.yani-catalog-shortcut-badge__color--red/);
assert.match(ui, /function openFilterMenu\(navigation\)/);
assert.match(ui, /filterModel\.activeCount\(baseParams\)/);
assert.match(ui, /yani-catalog-filter/);
assert.doesNotMatch(ui, /yani-catalog-filter selector/);
assert.doesNotMatch(ui, /yani-catalog-top selector/);
assert.doesNotMatch(ui, /yani-catalog-sort selector/);
assert.match(ui, /replaceWithFilters\(filterModel\.clear\(baseParams\)\)/);
assert.match(filters, /key: 'type'/);
assert.match(filters, /key: 'status'/);
assert.match(filters, /key: 'year'/);
assert.match(ui, /function isFirstCardRow\(card\)[\s\S]{0,900}Math\.abs\(currentCenter - firstCenter\)/);
assert.match(ui, /controller\.up = function \(\)[\s\S]{0,500}isFirstCardRow\(focusedCard\)[\s\S]{0,120}Controller\.toggle\('head'\)/);
assert.doesNotMatch(ui, /controller\.up = function \(\)[\s\S]{0,700}focusToolbar\(/);
assert.match(ui, /function focusCardInDirection\(direction\)[\s\S]{0,1600}candidateScore = Math\.abs\(distanceY\) \* 10000 \+ distanceX[\s\S]{0,500}collectionFocus\(target, collection, true\)/);
assert.match(ui, /controller\.down = function \(\)[\s\S]{0,250}focusCardInDirection\('down'\)[\s\S]{0,150}Navigator\.canmove\('down'\)/);
assert.match(ui, /controller\.down = function \(\)[\s\S]{0,500}comp\.scroll\.wheel\(300\)/);
assert.match(ui, /hover:focus\.yaniCatalogCard/);
assert.doesNotMatch(ui, /controller\.left = function \(\)[\s\S]{0,220}toolbarHasFocus/);
assert.doesNotMatch(ui, /controller\.right = function \(\)[\s\S]{0,220}toolbarHasFocus/);
assert.match(ui, /genreHeader\.length\) toolbar\.insertAfter\(genreHeader\)/);
const sortIconFunction = ui.match(/function catalogSortIcon\(key\) \{([\s\S]*?)\n    \}/);
assert.ok(sortIconFunction, 'catalog sorting icon map must exist');
const iconPaths = Array.from(sortIconFunction[1].matchAll(/<path d="([^"]+)"/g), (match) => match[1]);
assert.strictEqual(iconPaths.length, 7, 'every sorting action must define an SVG path');
assert.strictEqual(new Set(iconPaths).size, iconPaths.length, 'sorting actions must not reuse the same SVG path');
assert.match(css, /\.yani-catalog-command-deck[\s\S]{0,700}backdrop-filter/);
assert.match(css, /\.yani-catalog-command-deck__rail\s*\{[\s\S]{0,250}flex-direction:\s*row[\s\S]{0,250}overflow-x:\s*auto/);
assert.doesNotMatch(css, /\.yani-catalog-command-deck\s*\{[\s\S]{0,300}position:\s*absolute/);
assert.match(css, /\.yani-catalog-command-deck__heading/);
assert.match(css, /\.yani-catalog-filter__count/);
assert.match(css, /\.yani-catalog-view \.category-full[\s\S]{0,900}grid-template-columns:\s*repeat\(auto-fit/);
assert.match(css, /\.yani-catalog-view \.category-full[\s\S]{0,900}row-gap:\s*2\.8em/);
assert.match(css, /\.yani-catalog-view \.card \.card__title[\s\S]{0,600}margin-top:\s*\.85em/);
assert.match(css, /\.yani-user-lists-view \.items-cards[\s\S]{0,500}display:\s*flex/);
assert.match(css, /\.yani-card-rails \.items-cards[\s\S]{0,500}display:\s*flex/);
assert.match(css, /@media \(min-width: 70em\)[\s\S]{0,900}repeat\(7, minmax\(0, 1fr\)\)/);
assert.match(css, /\.yani-catalog-view \.category-full \.card[\s\S]{0,400}float:\s*none/);

['ru', 'en', 'uk'].forEach((language) => {
    ['catalog_sort_top', 'catalog_sort_new', 'catalog_sort_rating', 'catalog_sort_votes', 'catalog_sort_views', 'catalog_sort_title', 'catalog_sort_random', 'scroll_to_top', 'catalog_filters', 'catalog_shortcuts_numbers', 'catalog_filter_reset', 'catalog_filter_type', 'catalog_filter_status', 'catalog_filter_year'].forEach((key) => {
        assert.match(i18n, new RegExp(`messages\\.${language}\\.${key}\\s*=`));
    });
});

console.log('catalog controls contract checks passed');
