const assert = require('assert');
const fs = require('fs');

const build = fs.readFileSync('build.js', 'utf8');
const ui = fs.readFileSync('src/ui.js', 'utf8');
const detail = fs.readFileSync('src/ui-detail.js', 'utf8');
const css = fs.readFileSync('style.css', 'utf8');

assert.match(build, /'src\/ui-detail\.js'[\s\S]*'src\/ui\.js'/, 'detail module must load before the main UI');
assert.match(ui, /LampaYaniDetail\.create\(/, 'main UI must delegate Detail to LampaYaniDetail.create');
assert.doesNotMatch(ui, /function renderDetail\(cardData\)/, 'renderDetail must live in ui-detail.js');
assert.doesNotMatch(ui, /function createDetailEpisodeSummary\(cardData\)/, 'createDetailEpisodeSummary must live in ui-detail.js');
assert.doesNotMatch(ui, /function createDetailTranslations\(\)/, 'createDetailTranslations must live in ui-detail.js');
assert.match(detail, /function createDetailEpisodeSummary\(cardData\)/);
assert.match(detail, /function createDetailTranslations\(\)/);
assert.match(detail, /function createDetailListPanel\(cardData\)/);
assert.match(detail, /yani-detail__poster-column/);
assert.match(detail, /posterColumn\.append\(poster, listDock\)/, 'user-list controls must live below the poster');
assert.match(detail, /html\.append\(posterColumn, info\)/);
assert.doesNotMatch(detail, /info\.append\(listPanel\)/, 'user-list controls must not follow the primary Watch actions');
assert.match(detail, /shortcut: 'red'/);
assert.match(detail, /shortcut: 'green'/);
assert.match(detail, /shortcut: 'blue'/);
assert.match(detail, /shortcut: 'yellow'/);
assert.match(detail, /function handleRemoteListShortcut\(event\)/);
assert.match(detail, /function detailControllerIsActive\(\)/);
assert.match(detail, /function moveFromContentToListPanel\(\)/);
assert.match(detail, /function moveFromListPanelToContent\(\)/);
assert.match(detail, /listBridgeReturn = current\[0\]/);
assert.match(detail, /if \(moveFromContentToListPanel\(\)\) return/);
assert.match(detail, /if \(moveFromListPanelToContent\(\)\) return/);
assert.match(detail, /enabled\.controller \|\| enabled/);
assert.match(detail, /code === 183/);
assert.match(detail, /code === 184/);
assert.match(detail, /code === 185/);
assert.match(detail, /code === 186/);
assert.match(detail, /active \? LampaYaniApi\.removeFavorite\(cardData\.yani_id\) : LampaYaniApi\.addFavorite\(cardData\.yani_id\)/);
assert.match(detail, /active \? LampaYaniApi\.removeFromList\(cardData\.yani_id\) : LampaYaniApi\.addToList\(cardData\.yani_id, action\.id\)/);
assert.match(detail, /document\.addEventListener\('keydown', remoteListShortcutHandler, true\)/);
assert.match(detail, /document\.removeEventListener\('keydown', remoteListShortcutHandler, true\)/);
assert.match(detail, /function createDetailRatingAction\(cardData\)/);
assert.match(detail, /window\.LampaYaniDetail\s*=\s*\{create: create\}/);
assert.match(detail, /deps\.importVideosProgress\(data, videos\)/);
assert.match(ui, /importVideosProgress: importVideosProgress/);
assert.match(detail, /yani-detail__title selector/);
assert.match(detail, /toggle: function \(\) \{ detailFocus\.restore\(null, true\); \}/);
assert.match(detail, /titleFocus && titleFocus\.length \? titleFocus : html\.find\('\.yani-detail__title\.selector'\)/);
assert.match(detail, /yani-detail__poster selector/);
assert.match(detail, /function togglePosterViewer\(poster, cardData\)/);
assert.match(detail, /cardData\.yani_poster_full/, 'fullscreen poster must use the largest artwork, not the card-sized file');
assert.match(detail, /hover:enter\.yaniPoster click\.yaniPoster/);
assert.match(detail, /hover:enter click\.yaniLampaCard/);
assert.match(detail, /aria-expanded/);
assert.match(detail, /function closePosterViewer\(\)/);
assert.match(detail, /back: function \(\) \{ if \(!closePosterViewer\(\)\) goBack\(\); \}/);
assert.match(detail, /comp\.destroy[\s\S]{0,150}closePosterViewer\(\)/);
assert.match(css, /\.yani-detail__poster\.focus/);
assert.match(css, /\.yani-detail__list-dock\s*\{/);
assert.match(css, /\.yani-detail__list-shortcut--red/);
assert.match(css, /\.yani-poster-viewer\s*\{/);
assert.match(css, /\.yani-poster-viewer__image/);
assert.match(detail, /yani-detail__order-relation[\s\S]{0,180}appendYummyRating\(row, related/, 'release-order rating must be the final row item');
assert.match(css, /\.yani-detail__order-rating\s*\{[^}]*margin-left:\s*auto/, 'release-order rating must align to the right edge');

console.log('detail module contract checks passed');
